if: branch = master

os: linux
dist: xenial

services:
  - postgresql
  - xvfb

language: python 
python: "3.6"

addons:
  chrome: stable

install:
  - sudo apt install unzip
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis", ENV="DEVELOPMENT", TEST_ENV="TRAVIS_CI"

script:
 - ./manage.py test tests/ --tag=t1 --keepdb
 - ./manage.py test tests/ --tag=t2 --keepdb
 - ./manage.py test tests.test3 --keepdb
