if: branch = staging

language: python
python: '3.6'

install: pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis", ENV="DEVELOPMENT"

services: postgresql

script: ./manage.py test --tag="data-added"
